name: CI Build

on:
  push:
    branches:
      - main
    paths:
      - '**/src/**'
      - '**/.github/**'
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore
      
    - name: Sonar Scan
      run: |
        dotnet tool install --global dotnet-sonarscanner --version 5.2.0
        dotnet tool update dotnet-reportgenerator-globaltool -g --version 4.8.7

    - name: Test
      run: |
        dotnet test src --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage        
        reportgenerator "-reports:./coverage/**/coverage.cobertura.xml" "-targetdir:./sonarqubecoverage" "-reporttypes:SonarQube"        

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY      
      
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        projectBaseDir: src
        args: >
          -Dsonar.organization=kellysonrn
          -Dsonar.coverage.jacoco.xmlReportPaths="./sonarqubecoverage/SonarQube.xml
          -Dsonar.projectKey=KellysonRN_azure-functions-labs
          -Dsonar.projectBaseDir=.
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}      
